# Generated by Django 6.0.2 on 2026-03-03 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MovieListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('poster_path', models.CharField(blank=True, default='', max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EveryMovie.movielist')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('movie_list', 'tmdb_id')},
            },
        ),
    ]
